### ISSUE TITLE
xiaomi 12t twrp

### ISSUE THREAD

**Issue by ilkeroz17** [YuKongA/device_xiaomi_fuxi_TWRP#1]
hi help pls

my device hang :( 

xiaomi 12t twrp add pls help

OS | Android 12, MIUI 13
Chipset | Mediatek Dimensity 8100-Ultra
CPU | Octa-core (4x2.85 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)
GPU | Mali-G610 MC6

**Comment by YuKongA** [comment]
u just need to -ify [this](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_rubens-TWRP). and u can refer this [commit](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_matisse-TWRP/commit/e7c99b49b29daddefac2162aa3d4dab7fad96bac) or this [commit](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP/commit/9fba58e5eb579807722b3dd39e4fd5569c871b90)

**Comment by ilkeroz17** [comment]
My precious friend,

thank you for answering. I don't know how twrp is compiled. I hope you help me. can you guide me

https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_rubens-TWRP

**Comment by ilkeroz17** [comment]
> u just need to -ify [this](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_rubens-TWRP). and u can refer this [commit](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_matisse-TWRP/commit/e7c99b49b29daddefac2162aa3d4dab7fad96bac) or this [commit](https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP/commit/9fba58e5eb579807722b3dd39e4fd5569c871b90)

please can you give me an answer.

https://github.com/Vendor-Blobs/android_vendor_tree_xiaomi_plato

https://github.com/twrpdtgen/android_device_xiaomi_plato

**Comment by ilkeroz17** [comment]
friend,

https://github.com/ilkeroz17/device_xiaomi_rubens-TWRP/actions/runs/4373353311/jobs/7651420822

build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_rubens".
10:32:44 dumpvars failed with: exit status 1
Device rubens not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for rubens not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:[16](https://github.com/ilkeroz17/device_xiaomi_rubens-TWRP/actions/runs/4373353311/jobs/7651420822#step:11:17)0: error: Can not locate config makefile for product "twrp_rubens".
10:32:45 dumpvars failed with: exit status 1
Error: Process completed with exit code 1.

help pls
