### ISSUE TITLE
make adbd recoveryimage stuck at

### ISSUE THREAD

**Issue by adontoo** [YuKongA/device_xiaomi_fuxi_TWRP#2]
echo "module snapuserd missing dependencies: libgflags" && false
module snapuserd missing dependencies: libgflags

had try with this command :  sudo apt install libgflags-dev
still same as the error code

For built Orangefox recovery

**Comment by YuKongA** [comment]
Delete `<remove-project name="platform/external/gflags"  />`, then sync again.

**Comment by adontoo** [comment]
> Delete `<remove-project name="platform/external/gflags" />`, then sync again.

It worked ，thanks！But screen touch not working ，is there any suggestions?

**Comment by YuKongA** [comment]
Xiaomi 13 screen touch should work.  and if it is 13 Pro or other newer device, you will need to solve this problem yourself.

**Comment by adontoo** [comment]
> 

thanks
